#  Ops Director demo
version: '3'
networks:
  marklogicCluster:

services:
# Dev #######################################################

   dev1.local:
     image: "store/marklogicdb/marklogic-server:9.0-9-dev-centos"
     user: "root"
     ports:
       - 7997-8010:7997-8010
     hostname: dev1.local
     container_name: dev1.local
     volumes:
      - ./volumes/dev1.local/:/var/opt/MarkLogic/
     networks:
      - marklogicCluster

   dev2.local:
     image: "store/marklogicdb/marklogic-server:9.0-9-dev-centos"
     user: "root"
     ports:
       - 27997-28010:7997-8010
     hostname: dev2.local
     container_name: dev2.local
     volumes:
      - ./volumes/dev2.local/:/var/opt/MarkLogic/
     networks:
      - marklogicCluster

   dev3.local:
     image: "store/marklogicdb/marklogic-server:9.0-9-dev-centos"
     user: "root"
     ports:
       - 37997-38010:7997-8010
     hostname: dev3.local
     container_name: dev3.local
     volumes:
      - ./volumes/dev3.local/:/var/opt/MarkLogic/
     networks:
      - marklogicCluster

#################################################################



# OpsDirector ###################################################

   opsdirector.local:
     build: ./OpsDirector
     ports:
       - 51997-52010:7997-8010
     hostname: opsdirector.local
     container_name: opsdirector.local
     volumes:
      - ./volumes/opsdirector/:/var/opt/MarkLogic/
     networks:
      - marklogicCluster

#################################################################








